# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Find Banks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Find Banks
  pod 'Alamofire', '~> 4.9.0'
  
  #RxSwift
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa', '~> 5.0.0'
  
  #RxUtility
  pod 'RxSwiftExt', '~> 5.2.0'
  pod 'RxGoogleMaps', '~> 4.0.0'
  pod 'RxCoreLocation', '~> 1.4'

  target 'Find BanksTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mockingjay', '~> 3.0.0-alpha.1'
    pod 'Quick', '~> 2.2.0'
    pod 'RxNimble', '~> 4.7.0'
    pod 'RxTest', '~> 5.0.0'
    pod 'RxBlocking', '~> 5.0.0'
  end

  target 'Find BanksUITests' do
    # Pods for testing
  end

end
